# Generated by Django 3.0.6 on 2020-05-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="author",),
    ]
