# Generated by Django 3.0.6 on 2020-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_task_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="examples",
            field=models.CharField(default=1, max_length=240, verbose_name="Примеры"),
            preserve_default=False,
        ),
    ]
