# Generated by Django 3.0.6 on 2020-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_task_examples"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="likes",),
        migrations.AlterField(
            model_name="task",
            name="examples",
            field=models.TextField(max_length=240, verbose_name="Примеры"),
        ),
    ]
