# Generated by Django 3.0.6 on 2020-05-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_auto_20200530_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="solution",
            field=models.TextField(default="", max_length=5600),
        ),
    ]
